name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run setup helmfile
      uses: ./
    - name: test
      run: helmfile --version
